#############################################################################
# Makefile for building: libMPF.so.1.0.0
# Generated by qmake (3.0) (Qt 5.7.0)
# Project:  MPF.pro
# Template: lib
# Command: /usr/lib/qt/bin/qmake -spec linux-g++ -o Makefile MPF.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -IPages -IDelegates -ISystem -isystem /usr/include/qt -isystem /usr/include/qt/QtGui -isystem /usr/include/qt/QtCore -I. -I/usr/lib/qt/mkspecs/linux-g++
QMAKE         = /usr/lib/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MPF1.0.0
DISTDIR = /home/dude/MPF/.tmp/MPF1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-O1,--sort-common,--as-needed,-z,relro -shared -Wl,-soname,libMPF.so.1
LIBS          = $(SUBLIBS) -lsysfs -lparted -lblkid -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MPF.cpp \
		Delegates/checkBoxListDelegate.cpp \
		Delegates/checkBoxList.cpp \
		Delegates/comboBoxListDelegate.cpp \
		Delegates/lineEditListDelegate.cpp \
		Delegates/paritionSizeDelegate.cpp \
		Delegates/progressbarDelegate.cpp \
		Delegates/richTextDelegate.cpp \
		Pages/languagesPage.cpp \
		Pages/loadingpage.cpp \
		Pages/pageBase.cpp \
		System/chroot.cpp \
		System/drive.cpp \
		System/rootCommand.cpp \
		Pages/pagesgroup.cpp \
		Pages/groupSelector.cpp moc_MPF.cpp \
		moc_checkBoxListDelegate.cpp \
		moc_checkBoxList.cpp \
		moc_comboBoxListDelegate.cpp \
		moc_lineEditListDelegate.cpp \
		moc_partitionSizeDelegate.cpp \
		moc_progressbarDelegate.cpp \
		moc_richTextDelegate.cpp \
		moc_languagesPage.cpp \
		moc_loadingpage.cpp \
		moc_pageBase.cpp \
		moc_chroot.cpp \
		moc_rootCommand.cpp \
		moc_pagesgroup.cpp \
		moc_groupSelector.cpp
OBJECTS       = MPF.o \
		checkBoxListDelegate.o \
		checkBoxList.o \
		comboBoxListDelegate.o \
		lineEditListDelegate.o \
		paritionSizeDelegate.o \
		progressbarDelegate.o \
		richTextDelegate.o \
		languagesPage.o \
		loadingpage.o \
		pageBase.o \
		chroot.o \
		drive.o \
		rootCommand.o \
		pagesgroup.o \
		groupSelector.o \
		moc_MPF.o \
		moc_checkBoxListDelegate.o \
		moc_checkBoxList.o \
		moc_comboBoxListDelegate.o \
		moc_lineEditListDelegate.o \
		moc_partitionSizeDelegate.o \
		moc_progressbarDelegate.o \
		moc_richTextDelegate.o \
		moc_languagesPage.o \
		moc_loadingpage.o \
		moc_pageBase.o \
		moc_chroot.o \
		moc_rootCommand.o \
		moc_pagesgroup.o \
		moc_groupSelector.o
DIST          = /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDGantt2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MimeTreeParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_SendLater.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		MPF.pro MPF.h \
		Delegates/checkBoxListDelegate.hpp \
		Delegates/checkBoxList.hpp \
		Delegates/comboBoxListDelegate.hpp \
		Delegates/lineEditListDelegate.hpp \
		Delegates/partitionSizeDelegate.hpp \
		Delegates/progressbarDelegate.hpp \
		Delegates/richTextDelegate.hpp \
		Pages/languagesPage.hpp \
		Pages/loadingpage.hpp \
		Pages/pageBase.hpp \
		System/chroot.hpp \
		System/drive.hpp \
		System/driveList.hpp \
		System/rootCommand.hpp \
		Pages/pagesgroup.hpp \
		Pages/groupSelector.hpp MPF.cpp \
		Delegates/checkBoxListDelegate.cpp \
		Delegates/checkBoxList.cpp \
		Delegates/comboBoxListDelegate.cpp \
		Delegates/lineEditListDelegate.cpp \
		Delegates/paritionSizeDelegate.cpp \
		Delegates/progressbarDelegate.cpp \
		Delegates/richTextDelegate.cpp \
		Pages/languagesPage.cpp \
		Pages/loadingpage.cpp \
		Pages/pageBase.cpp \
		System/chroot.cpp \
		System/drive.cpp \
		System/rootCommand.cpp \
		Pages/pagesgroup.cpp \
		Pages/groupSelector.cpp
QMAKE_TARGET  = MPF
DESTDIR       = release/
TARGET        = libMPF.so.1.0.0
TARGETA       = release/libMPF.a
TARGET0       = libMPF.so
TARGETD       = libMPF.so.1.0.0
TARGET1       = libMPF.so.1
TARGET2       = libMPF.so.1.0


first: all
####### Build rules

release/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@test -d release/ || mkdir -p release/
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)
	-$(DEL_FILE) release/$(TARGET)
	-$(MOVE) $(TARGET)  release/ 
	-$(DEL_FILE) release/$(TARGET0)
	-$(DEL_FILE) release/$(TARGET1)
	-$(DEL_FILE) release/$(TARGET2)
	-$(MOVE) $(TARGET0) release/ 
	-$(MOVE) $(TARGET1) release/ 
	-$(MOVE) $(TARGET2) release/ 



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: MPF.pro /usr/lib/qt/mkspecs/linux-g++/qmake.conf /usr/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/lib/qt/mkspecs/common/unix.conf \
		/usr/lib/qt/mkspecs/common/linux.conf \
		/usr/lib/qt/mkspecs/common/sanitize.conf \
		/usr/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/lib/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt/mkspecs/common/g++-base.conf \
		/usr/lib/qt/mkspecs/common/g++-unix.conf \
		/usr/lib/qt/mkspecs/qconfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri \
		/usr/lib/qt/mkspecs/modules/qt_Attica.pri \
		/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_EventViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_FollowupReminder.pri \
		/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri \
		/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri \
		/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivities.pri \
		/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri \
		/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri \
		/usr/lib/qt/mkspecs/modules/qt_KArchive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KAuth.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBlog.pri \
		/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KCrash.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri \
		/usr/lib/qt/mkspecs/modules/qt_KdepimDBusInterfaces.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDESu.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDGantt2.pri \
		/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri \
		/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri \
		/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri \
		/usr/lib/qt/mkspecs/modules/qt_KHtml.pri \
		/usr/lib/qt/mkspecs/modules/qt_KI18n.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri \
		/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJS.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri \
		/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KMime.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri \
		/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri \
		/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri \
		/usr/lib/qt/mkspecs/modules/qt_KParts.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeople.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri \
		/usr/lib/qt/mkspecs/modules/qt_KPty.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KRunner.pri \
		/usr/lib/qt/mkspecs/modules/qt_KScreen.pri \
		/usr/lib/qt/mkspecs/modules/qt_KService.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieve.pri \
		/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_KTNef.pri \
		/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWallet.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri \
		/usr/lib/qt/mkspecs/modules/qt_KXmlRpcClient.pri \
		/usr/lib/qt/mkspecs/modules/qt_Ldap.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri \
		/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri \
		/usr/lib/qt/mkspecs/modules/qt_Mbox.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageList.pri \
		/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri \
		/usr/lib/qt/mkspecs/modules/qt_MimeTreeParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri \
		/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri \
		/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri \
		/usr/lib/qt/mkspecs/modules/qt_Prison.pri \
		/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri \
		/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri \
		/usr/lib/qt/mkspecs/modules/qt_SendLater.pri \
		/usr/lib/qt/mkspecs/modules/qt_Solid.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri \
		/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri \
		/usr/lib/qt/mkspecs/modules/qt_Syndication.pri \
		/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri \
		/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri \
		/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri \
		/usr/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/lib/qt/mkspecs/features/qt_config.prf \
		/usr/lib/qt/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt/mkspecs/features/default_pre.prf \
		/usr/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/lib/qt/mkspecs/features/default_post.prf \
		/usr/lib/qt/mkspecs/features/warn_on.prf \
		/usr/lib/qt/mkspecs/features/qt.prf \
		/usr/lib/qt/mkspecs/features/resources.prf \
		/usr/lib/qt/mkspecs/features/moc.prf \
		/usr/lib/qt/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt/mkspecs/features/unix/thread.prf \
		/usr/lib/qt/mkspecs/features/file_copies.prf \
		/usr/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt/mkspecs/features/exceptions.prf \
		/usr/lib/qt/mkspecs/features/yacc.prf \
		/usr/lib/qt/mkspecs/features/lex.prf \
		MPF.pro \
		/usr/lib/libQt5Gui.prl \
		/usr/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ -o Makefile MPF.pro
/usr/lib/qt/mkspecs/features/spec_pre.prf:
/usr/lib/qt/mkspecs/common/unix.conf:
/usr/lib/qt/mkspecs/common/linux.conf:
/usr/lib/qt/mkspecs/common/sanitize.conf:
/usr/lib/qt/mkspecs/common/gcc-base.conf:
/usr/lib/qt/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt/mkspecs/common/g++-base.conf:
/usr/lib/qt/mkspecs/common/g++-unix.conf:
/usr/lib/qt/mkspecs/qconfig.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiAgentBase.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiContact.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiCore.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiMime.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiNotes.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_AkonadiXml.pri:
/usr/lib/qt/mkspecs/modules/qt_Attica.pri:
/usr/lib/qt/mkspecs/modules/qt_BluezQt.pri:
/usr/lib/qt/mkspecs/modules/qt_CalendarSupport.pri:
/usr/lib/qt/mkspecs/modules/qt_EventViews.pri:
/usr/lib/qt/mkspecs/modules/qt_FollowupReminder.pri:
/usr/lib/qt/mkspecs/modules/qt_GrantleeTheme.pri:
/usr/lib/qt/mkspecs/modules/qt_Gravatar.pri:
/usr/lib/qt/mkspecs/modules/qt_IncidenceEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivities.pri:
/usr/lib/qt/mkspecs/modules/qt_KActivitiesStats.pri:
/usr/lib/qt/mkspecs/modules/qt_KaddressbookGrantlee.pri:
/usr/lib/qt/mkspecs/modules/qt_KAlarmCal.pri:
/usr/lib/qt/mkspecs/modules/qt_KArchive.pri:
/usr/lib/qt/mkspecs/modules/qt_KAuth.pri:
/usr/lib/qt/mkspecs/modules/qt_KBlog.pri:
/usr/lib/qt/mkspecs/modules/qt_KBookmarks.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KCalUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCMUtils.pri:
/usr/lib/qt/mkspecs/modules/qt_KCodecs.pri:
/usr/lib/qt/mkspecs/modules/qt_KCompletion.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KConfigWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KCrash.pri:
/usr/lib/qt/mkspecs/modules/qt_KDBusAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KDeclarative.pri:
/usr/lib/qt/mkspecs/modules/qt_KdepimDBusInterfaces.pri:
/usr/lib/qt/mkspecs/modules/qt_KDESu.pri:
/usr/lib/qt/mkspecs/modules/qt_KDEWebKit.pri:
/usr/lib/qt/mkspecs/modules/qt_KDGantt2.pri:
/usr/lib/qt/mkspecs/modules/qt_KDNSSD.pri:
/usr/lib/qt/mkspecs/modules/qt_KEmoticons.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIBlogger.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICalendar.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIContacts.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPICore.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIDrive.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPILatitude.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPIMaps.pri:
/usr/lib/qt/mkspecs/modules/qt_KGAPITasks.pri:
/usr/lib/qt/mkspecs/modules/qt_KGlobalAccel.pri:
/usr/lib/qt/mkspecs/modules/qt_KGuiAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KHolidays.pri:
/usr/lib/qt/mkspecs/modules/qt_KHtml.pri:
/usr/lib/qt/mkspecs/modules/qt_KI18n.pri:
/usr/lib/qt/mkspecs/modules/qt_KIconThemes.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdentityManagement.pri:
/usr/lib/qt/mkspecs/modules/qt_KIdleTime.pri:
/usr/lib/qt/mkspecs/modules/qt_KIMAP.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOFileWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KIOWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemModels.pri:
/usr/lib/qt/mkspecs/modules/qt_KItemViews.pri:
/usr/lib/qt/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KJS.pri:
/usr/lib/qt/mkspecs/modules/qt_KJSApi.pri:
/usr/lib/qt/mkspecs/modules/qt_KJsEmbed.pri:
/usr/lib/qt/mkspecs/modules/qt_KMailTransport.pri:
/usr/lib/qt/mkspecs/modules/qt_KManageSieve.pri:
/usr/lib/qt/mkspecs/modules/qt_KMime.pri:
/usr/lib/qt/mkspecs/modules/qt_KNewStuff.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifications.pri:
/usr/lib/qt/mkspecs/modules/qt_KNotifyConfig.pri:
/usr/lib/qt/mkspecs/modules/qt_KNTLM.pri:
/usr/lib/qt/mkspecs/modules/qt_KontactInterface.pri:
/usr/lib/qt/mkspecs/modules/qt_KParts.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeople.pri:
/usr/lib/qt/mkspecs/modules/qt_KPeopleWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KPIMTextEdit.pri:
/usr/lib/qt/mkspecs/modules/qt_KPlotting.pri:
/usr/lib/qt/mkspecs/modules/qt_KPty.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossCore.pri:
/usr/lib/qt/mkspecs/modules/qt_KrossUi.pri:
/usr/lib/qt/mkspecs/modules/qt_KRunner.pri:
/usr/lib/qt/mkspecs/modules/qt_KScreen.pri:
/usr/lib/qt/mkspecs/modules/qt_KService.pri:
/usr/lib/qt/mkspecs/modules/qt_KSieve.pri:
/usr/lib/qt/mkspecs/modules/qt_KSieveUi.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextEditor.pri:
/usr/lib/qt/mkspecs/modules/qt_KTextWidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_KTNef.pri:
/usr/lib/qt/mkspecs/modules/qt_KUnitConversion.pri:
/usr/lib/qt/mkspecs/modules/qt_KWallet.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandClient.pri:
/usr/lib/qt/mkspecs/modules/qt_KWaylandServer.pri:
/usr/lib/qt/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_KWindowSystem.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlGui.pri:
/usr/lib/qt/mkspecs/modules/qt_KXmlRpcClient.pri:
/usr/lib/qt/mkspecs/modules/qt_Ldap.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webengine_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/lib/qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/lib/qt/mkspecs/modules/qt_Libkdepim.pri:
/usr/lib/qt/mkspecs/modules/qt_Libkleo.pri:
/usr/lib/qt/mkspecs/modules/qt_MailCommon.pri:
/usr/lib/qt/mkspecs/modules/qt_MailImporter.pri:
/usr/lib/qt/mkspecs/modules/qt_Mbox.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageComposer.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageCore.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageList.pri:
/usr/lib/qt/mkspecs/modules/qt_MessageViewer.pri:
/usr/lib/qt/mkspecs/modules/qt_MimeTreeParser.pri:
/usr/lib/qt/mkspecs/modules/qt_ModemManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_NetworkManagerQt.pri:
/usr/lib/qt/mkspecs/modules/qt_phonon4qt5.pri:
/usr/lib/qt/mkspecs/modules/qt_PimCommon.pri:
/usr/lib/qt/mkspecs/modules/qt_Prison.pri:
/usr/lib/qt/mkspecs/modules/qt_QGpgme.pri:
/usr/lib/qt/mkspecs/modules/qt_QuickAddons.pri:
/usr/lib/qt/mkspecs/modules/qt_SendLater.pri:
/usr/lib/qt/mkspecs/modules/qt_Solid.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetCore.pri:
/usr/lib/qt/mkspecs/modules/qt_SonnetUi.pri:
/usr/lib/qt/mkspecs/modules/qt_Syndication.pri:
/usr/lib/qt/mkspecs/modules/qt_TemplateParser.pri:
/usr/lib/qt/mkspecs/modules/qt_ThreadWeaver.pri:
/usr/lib/qt/mkspecs/modules/qt_WebEngineViewer.pri:
/usr/lib/qt/mkspecs/features/qt_functions.prf:
/usr/lib/qt/mkspecs/features/qt_config.prf:
/usr/lib/qt/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt/mkspecs/features/default_pre.prf:
/usr/lib/qt/mkspecs/features/resolve_config.prf:
/usr/lib/qt/mkspecs/features/default_post.prf:
/usr/lib/qt/mkspecs/features/warn_on.prf:
/usr/lib/qt/mkspecs/features/qt.prf:
/usr/lib/qt/mkspecs/features/resources.prf:
/usr/lib/qt/mkspecs/features/moc.prf:
/usr/lib/qt/mkspecs/features/unix/opengl.prf:
/usr/lib/qt/mkspecs/features/unix/thread.prf:
/usr/lib/qt/mkspecs/features/file_copies.prf:
/usr/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/lib/qt/mkspecs/features/exceptions.prf:
/usr/lib/qt/mkspecs/features/yacc.prf:
/usr/lib/qt/mkspecs/features/lex.prf:
MPF.pro:
/usr/lib/libQt5Gui.prl:
/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ -o Makefile MPF.pro

qmake_all: FORCE


all: Makefile release/$(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents MPF.h Delegates/checkBoxListDelegate.hpp Delegates/checkBoxList.hpp Delegates/comboBoxListDelegate.hpp Delegates/lineEditListDelegate.hpp Delegates/partitionSizeDelegate.hpp Delegates/progressbarDelegate.hpp Delegates/richTextDelegate.hpp Pages/languagesPage.hpp Pages/loadingpage.hpp Pages/pageBase.hpp System/chroot.hpp System/drive.hpp System/driveList.hpp System/rootCommand.hpp Pages/pagesgroup.hpp Pages/groupSelector.hpp $(DISTDIR)/
	$(COPY_FILE) --parents MPF.cpp Delegates/checkBoxListDelegate.cpp Delegates/checkBoxList.cpp Delegates/comboBoxListDelegate.cpp Delegates/lineEditListDelegate.cpp Delegates/paritionSizeDelegate.cpp Delegates/progressbarDelegate.cpp Delegates/richTextDelegate.cpp Pages/languagesPage.cpp Pages/loadingpage.cpp Pages/pageBase.cpp System/chroot.cpp System/drive.cpp System/rootCommand.cpp Pages/pagesgroup.cpp Pages/groupSelector.cpp $(DISTDIR)/
	$(COPY_FILE) --parents /home/dude/MPF/Translations/en.ts /home/dude/MPF/Translations/ar.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) release/$(TARGET) 
	-$(DEL_FILE) release/$(TARGET0) release/$(TARGET1) release/$(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_MPF.cpp moc_checkBoxListDelegate.cpp moc_checkBoxList.cpp moc_comboBoxListDelegate.cpp moc_lineEditListDelegate.cpp moc_partitionSizeDelegate.cpp moc_progressbarDelegate.cpp moc_richTextDelegate.cpp moc_languagesPage.cpp moc_loadingpage.cpp moc_pageBase.cpp moc_chroot.cpp moc_rootCommand.cpp moc_pagesgroup.cpp moc_groupSelector.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MPF.cpp moc_checkBoxListDelegate.cpp moc_checkBoxList.cpp moc_comboBoxListDelegate.cpp moc_lineEditListDelegate.cpp moc_partitionSizeDelegate.cpp moc_progressbarDelegate.cpp moc_richTextDelegate.cpp moc_languagesPage.cpp moc_loadingpage.cpp moc_pageBase.cpp moc_chroot.cpp moc_rootCommand.cpp moc_pagesgroup.cpp moc_groupSelector.cpp
moc_MPF.cpp: ui_MPF.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		Pages/pagesgroup.hpp \
		MPF.h \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include MPF.h -o moc_MPF.cpp

moc_checkBoxListDelegate.cpp: Delegates/checkBoxListDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/checkBoxListDelegate.hpp -o moc_checkBoxListDelegate.cpp

moc_checkBoxList.cpp: Delegates/checkBoxListDelegate.hpp \
		Delegates/checkBoxList.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/checkBoxList.hpp -o moc_checkBoxList.cpp

moc_comboBoxListDelegate.cpp: Delegates/comboBoxListDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/comboBoxListDelegate.hpp -o moc_comboBoxListDelegate.cpp

moc_lineEditListDelegate.cpp: Delegates/lineEditListDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/lineEditListDelegate.hpp -o moc_lineEditListDelegate.cpp

moc_partitionSizeDelegate.cpp: Delegates/partitionSizeDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/partitionSizeDelegate.hpp -o moc_partitionSizeDelegate.cpp

moc_progressbarDelegate.cpp: Delegates/progressbarDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/progressbarDelegate.hpp -o moc_progressbarDelegate.cpp

moc_richTextDelegate.cpp: Delegates/richTextDelegate.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Delegates/richTextDelegate.hpp -o moc_richTextDelegate.cpp

moc_languagesPage.cpp: Pages/pageBase.hpp \
		ui_languagesPage.h \
		Pages/languagesPage.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Pages/languagesPage.hpp -o moc_languagesPage.cpp

moc_loadingpage.cpp: Pages/pageBase.hpp \
		ui_loadingPage.h \
		Pages/loadingpage.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Pages/loadingpage.hpp -o moc_loadingpage.cpp

moc_pageBase.cpp: Pages/pageBase.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Pages/pageBase.hpp -o moc_pageBase.cpp

moc_chroot.cpp: System/chroot.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include System/chroot.hpp -o moc_chroot.cpp

moc_rootCommand.cpp: System/rootCommand.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include System/rootCommand.hpp -o moc_rootCommand.cpp

moc_pagesgroup.cpp: Pages/pageBase.hpp \
		Pages/pagesgroup.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Pages/pagesgroup.hpp -o moc_pagesgroup.cpp

moc_groupSelector.cpp: ui_groupSelector.h \
		MPF.h \
		ui_MPF.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		Pages/pagesgroup.hpp \
		Pages/groupSelector.hpp \
		/usr/lib/qt/bin/moc
	/usr/lib/qt/bin/moc $(DEFINES) -I/usr/lib/qt/mkspecs/linux-g++ -I/home/dude/MPF -I/home/dude/MPF -I/home/dude/MPF/Pages -I/home/dude/MPF/Delegates -I/home/dude/MPF/System -I/usr/include/qt -I/usr/include/qt/QtGui -I/usr/include/qt/QtCore -I/usr/include/c++/6.1.1 -I/usr/include/c++/6.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/6.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/6.1.1/include-fixed -I/usr/include Pages/groupSelector.hpp -o moc_groupSelector.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

MPF.o: MPF.cpp MPF.h \
		ui_MPF.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		Pages/pagesgroup.hpp \
		Pages/languagesPage.hpp \
		ui_languagesPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MPF.o MPF.cpp

checkBoxListDelegate.o: Delegates/checkBoxListDelegate.cpp Delegates/checkBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkBoxListDelegate.o Delegates/checkBoxListDelegate.cpp

checkBoxList.o: Delegates/checkBoxList.cpp Delegates/checkBoxList.hpp \
		Delegates/checkBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkBoxList.o Delegates/checkBoxList.cpp

comboBoxListDelegate.o: Delegates/comboBoxListDelegate.cpp Delegates/comboBoxListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o comboBoxListDelegate.o Delegates/comboBoxListDelegate.cpp

lineEditListDelegate.o: Delegates/lineEditListDelegate.cpp Delegates/lineEditListDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lineEditListDelegate.o Delegates/lineEditListDelegate.cpp

paritionSizeDelegate.o: Delegates/paritionSizeDelegate.cpp Delegates/partitionSizeDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paritionSizeDelegate.o Delegates/paritionSizeDelegate.cpp

progressbarDelegate.o: Delegates/progressbarDelegate.cpp Delegates/progressbarDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progressbarDelegate.o Delegates/progressbarDelegate.cpp

richTextDelegate.o: Delegates/richTextDelegate.cpp Delegates/richTextDelegate.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o richTextDelegate.o Delegates/richTextDelegate.cpp

languagesPage.o: Pages/languagesPage.cpp Pages/languagesPage.hpp \
		Pages/pageBase.hpp \
		ui_languagesPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o languagesPage.o Pages/languagesPage.cpp

loadingpage.o: Pages/loadingpage.cpp Pages/loadingpage.hpp \
		Pages/pageBase.hpp \
		ui_loadingPage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loadingpage.o Pages/loadingpage.cpp

pageBase.o: Pages/pageBase.cpp Pages/pageBase.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pageBase.o Pages/pageBase.cpp

chroot.o: System/chroot.cpp System/chroot.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chroot.o System/chroot.cpp

drive.o: System/drive.cpp System/drive.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drive.o System/drive.cpp

rootCommand.o: System/rootCommand.cpp System/rootCommand.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rootCommand.o System/rootCommand.cpp

pagesgroup.o: Pages/pagesgroup.cpp Pages/pagesgroup.hpp \
		Pages/pageBase.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pagesgroup.o Pages/pagesgroup.cpp

groupSelector.o: Pages/groupSelector.cpp Pages/groupSelector.hpp \
		ui_groupSelector.h \
		MPF.h \
		ui_MPF.h \
		Pages/pageBase.hpp \
		Pages/loadingpage.hpp \
		ui_loadingPage.h \
		Pages/pagesgroup.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o groupSelector.o Pages/groupSelector.cpp

moc_MPF.o: moc_MPF.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MPF.o moc_MPF.cpp

moc_checkBoxListDelegate.o: moc_checkBoxListDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkBoxListDelegate.o moc_checkBoxListDelegate.cpp

moc_checkBoxList.o: moc_checkBoxList.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkBoxList.o moc_checkBoxList.cpp

moc_comboBoxListDelegate.o: moc_comboBoxListDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_comboBoxListDelegate.o moc_comboBoxListDelegate.cpp

moc_lineEditListDelegate.o: moc_lineEditListDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_lineEditListDelegate.o moc_lineEditListDelegate.cpp

moc_partitionSizeDelegate.o: moc_partitionSizeDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_partitionSizeDelegate.o moc_partitionSizeDelegate.cpp

moc_progressbarDelegate.o: moc_progressbarDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_progressbarDelegate.o moc_progressbarDelegate.cpp

moc_richTextDelegate.o: moc_richTextDelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_richTextDelegate.o moc_richTextDelegate.cpp

moc_languagesPage.o: moc_languagesPage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_languagesPage.o moc_languagesPage.cpp

moc_loadingpage.o: moc_loadingpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_loadingpage.o moc_loadingpage.cpp

moc_pageBase.o: moc_pageBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pageBase.o moc_pageBase.cpp

moc_chroot.o: moc_chroot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chroot.o moc_chroot.cpp

moc_rootCommand.o: moc_rootCommand.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rootCommand.o moc_rootCommand.cpp

moc_pagesgroup.o: moc_pagesgroup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pagesgroup.o moc_pagesgroup.cpp

moc_groupSelector.o: moc_groupSelector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_groupSelector.o moc_groupSelector.cpp

####### Install

install_installfiles2: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/MPF/System || mkdir -p $(INSTALL_ROOT)/usr/include/MPF/System
	-$(INSTALL_FILE) /home/dude/MPF/System/chroot.hpp $(INSTALL_ROOT)/usr/include/MPF/System/
	-$(INSTALL_FILE) /home/dude/MPF/System/drive.hpp $(INSTALL_ROOT)/usr/include/MPF/System/
	-$(INSTALL_FILE) /home/dude/MPF/System/driveList.hpp $(INSTALL_ROOT)/usr/include/MPF/System/
	-$(INSTALL_FILE) /home/dude/MPF/System/rootCommand.hpp $(INSTALL_ROOT)/usr/include/MPF/System/

uninstall_installfiles2: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/System/rootCommand.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/System/driveList.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/System/drive.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/System/chroot.hpp
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/MPF/System/ 


install_installfiles3: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/MPF/Delegates || mkdir -p $(INSTALL_ROOT)/usr/include/MPF/Delegates
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/checkBoxList.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/checkBoxListDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/comboBoxListDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/lineEditListDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/partitionSizeDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/progressbarDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/
	-$(INSTALL_FILE) /home/dude/MPF/Delegates/richTextDelegate.hpp $(INSTALL_ROOT)/usr/include/MPF/Delegates/

uninstall_installfiles3: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/richTextDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/progressbarDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/partitionSizeDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/lineEditListDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/comboBoxListDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/checkBoxListDelegate.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Delegates/checkBoxList.hpp
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/MPF/Delegates/ 


install_installfiles4: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/MPF/Pages || mkdir -p $(INSTALL_ROOT)/usr/include/MPF/Pages
	-$(INSTALL_FILE) /home/dude/MPF/Pages/groupSelector.hpp $(INSTALL_ROOT)/usr/include/MPF/Pages/
	-$(INSTALL_FILE) /home/dude/MPF/Pages/languagesPage.hpp $(INSTALL_ROOT)/usr/include/MPF/Pages/
	-$(INSTALL_FILE) /home/dude/MPF/Pages/loadingpage.hpp $(INSTALL_ROOT)/usr/include/MPF/Pages/
	-$(INSTALL_FILE) /home/dude/MPF/Pages/pageBase.hpp $(INSTALL_ROOT)/usr/include/MPF/Pages/
	-$(INSTALL_FILE) /home/dude/MPF/Pages/pagesgroup.hpp $(INSTALL_ROOT)/usr/include/MPF/Pages/

uninstall_installfiles4: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Pages/pagesgroup.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Pages/pageBase.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Pages/loadingpage.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Pages/languagesPage.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Pages/groupSelector.hpp
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/MPF/Pages/ 


install_installfiles5: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/MPF/ || mkdir -p $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/MPF.h $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/ui_groupSelector.h $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/ui_languagesPage.h $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/ui_loadingPage.h $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/ui_MPF.h $(INSTALL_ROOT)/usr/include/MPF/
	-$(INSTALL_FILE) /home/dude/MPF/ui_pageBase.h $(INSTALL_ROOT)/usr/include/MPF/

uninstall_installfiles5: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/ui_pageBase.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/ui_MPF.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/ui_loadingPage.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/ui_languagesPage.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/ui_groupSelector.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/MPF.h
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/MPF/ 


install_installfiles6: first FORCE
	@test -d $(INSTALL_ROOT)/usr/include/MPF/Translations/ || mkdir -p $(INSTALL_ROOT)/usr/include/MPF/Translations/
	-$(INSTALL_FILE) /home/dude/MPF/Translations/ar.qm $(INSTALL_ROOT)/usr/include/MPF/Translations/
	-$(INSTALL_FILE) /home/dude/MPF/Translations/en.qm $(INSTALL_ROOT)/usr/include/MPF/Translations/

uninstall_installfiles6: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Translations/en.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/include/MPF/Translations/ar.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/include/MPF/Translations/ 


install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_PROGRAM) release/$(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_installfiles2 install_installfiles3 install_installfiles4 install_installfiles5 install_installfiles6 install_target  FORCE

uninstall: uninstall_installfiles2 uninstall_installfiles3 uninstall_installfiles4 uninstall_installfiles5 uninstall_installfiles6 uninstall_target  FORCE

FORCE:

